#!/bin/sh

# TODO: save base branch (default to origin/master) paired with current branch.
# Subsequent code-review commands should use this base branch.

# TODO: think about renaming this to "init" if there's no corresponding "end"
# subcommand.


SCRIPT="$(dirname "$0")"
source "$SCRIPT/code-review-database"


create_database_if_not_exists

merge_base='origin/master'
if [ $# -eq 1 ]; then
	merge_base="$1"
fi

create_merge_base_from_current "$merge_base"
