#!/bin/sh

# Copyright (c) 2019  Teddy Wing
#
# This file is part of Code Review.
#
# Code Review is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Code Review is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Code Review. If not, see <https://www.gnu.org/licenses/>.

# TODO: save base branch (default to origin/master) paired with current branch.
# Subsequent code-review commands should use this base branch.

# TODO: think about renaming this to "init" if there's no corresponding "end"
# subcommand.


SCRIPT="$(dirname "$0")"
source "$SCRIPT/code-review-database"


create_database_if_not_exists

if [ $# -eq 1 ]; then
	merge_base="$1"
	create_merge_base_from_current "$merge_base"
fi
