#!/bin/sh

# Copyright (c) 2023  Teddy Wing
#
# This file is part of Code Review.
#
# Code Review is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Code Review is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Code Review. If not, see <https://www.gnu.org/licenses/>.


# Like code-review-start, but get the merge base from the associated GitHub
# pull request.

current_branch_name() {
	git rev-parse --abbrev-ref HEAD
}

github_merge_base() {
	# Find a pull request with a HEAD branch matching the name of the current
	# branch. Get that pull request's base (merge target) branch.
	gh api \
		repos/:owner/:repo/pulls \
		--jq=".[]
			| select(.head.ref == \"$(current_branch_name)\")
			| .base.ref"
}

code-review-start "$(github_merge_base)"
