#!/usr/bin/env bash

# Copyright (c) 2019  Teddy Wing
#
# This file is part of Code Review.
#
# Code Review is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Code Review is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Code Review. If not, see <https://www.gnu.org/licenses/>.

SCRIPT="$(dirname "$0")"
source "$SCRIPT/code-review-database"


review_base="$(get_merge_base)"

# Remove dot ranges at the end of a revision as Fugitive doesn't support them.
shopt -s extglob
review_base_without_dots="${review_base%%?(..|...)}"

vim -c "tabdo Gdiff $review_base_without_dots" -p $(code-review changed-files)
