#!/bin/sh

# Copyright (c) 2018  Teddy Wing
#
# This file is part of Code Review.
#
# Code Review is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Code Review is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Code Review. If not, see <https://www.gnu.org/licenses/>.

git-review () {
	local EX_USAGE=64

	if [ "$#" -ne 1 ]; then
		return $EX_USAGE
	fi

	local pr_id="$1"
	local path="$(git rev-parse --show-toplevel)"
	local worktree_dir="$path+review-$pr_id"

	git fetch origin pull/$pr_id/head:pr/$pr_id \
		&& git worktree add "$worktree_dir" pr/$pr_id

	cd "$worktree_dir"
}
